POST http://127.0.0.1:8000/api/blog/login
Content-Type: application/json

{"username": "elad134","password":"tk1234"}

###

POST http://127.0.0.1:8000/api/blog/signup
Content-Type: application/json

{"username": "elad134","password":"tk1234", "email" : "eladtvil@gmail.com"}

###
GET  http://127.0.0.1:8000/api/blog/test_token
Content-Type: application/json
{}