# Generated by Django 5.0.1 on 2024-02-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.CharField(blank=True, default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FMaccabi_Tel_Aviv_F.C.&psig=AOvVaw3NILBkS4Lb6XsfoR3C-gIr&ust=1706994615710000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCPjcqs_IjYQDFQAAAAAdAAAAABAE', max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
