# Generated by Django 5.0.1 on 2024-02-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog_img_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.CharField(blank=True, default='https://www.google.com/search?q=maccabi+tel+aviv&sca_esv=945791448f04a98e&sxsrf=ACQVn08uJGttpoCDYNajc7M8BzWeI4iEyQ:1707322257455&tbm=isch&source=iu&ictx=1&vet=1&fir=d2fZAe61xxGGwM%252CIuHQhCZe2HgNQM%252C%252Fm%252F03j70d%253BORiyf6RMIB8ONM%252C1JlG9BtSi0QDeM%252C_%253B1edNqG61IGTXnM%252C0Wz0MKgN4r5u7M%252C_%253BZ8tyo6Ipmp8s3M%252CkuYiACvgvl0kWM%252C_%253BxGeTpL1xxjgtiM%252CkGDRX8SRwwZHqM%252C_%253B17DHT74ZwtRtMM%252CmmG9Qqk388Z80M%252C_%253BJd2ozHdzoLtb2M%252CMPorlEILnILE5M%252C_&usg=AI4_-kSCVzWCGnTFFj2pcKKe2fr_QLYA8A&sa=X&ved=2ahUKEwjPpbCFz5mEAxV70gIHHaOEBmwQ_B16BAhVEAE#imgrc=d2fZAe61xxGGwM', max_length=700, null=True),
        ),
    ]
